services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    command: ./scripts/dev.sh

  build:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: ./scripts/build.sh

  site:
    build:
      context: .
      target: runtime
    ports:
      - "8080:80"
