server {
    listen 80;
    server_name _;
    absolute_redirect off;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;
    gzip on;
    gzip_types application/wasm application/octet-stream application/javascript text/css text/plain application/json;
    gzip_min_length 1024;
    location = /BufoClicker { return 301 /BufoClicker/; }
    location /BufoClicker/ { alias /usr/share/nginx/html/; }
    location / { try_files $uri $uri/ =404; }
}
