const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(process.env.BUFO_SITE_DIR||'dist');
(async()=>{
 const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',file.endsWith('.wasm')?'application/wasm':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}}).listen(9136);
 const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:9136/');await page.waitForSelector('#bufo');
 const evidence=await page.evaluate(()=>{document.querySelector('#bufo').click();document.querySelector('#bufo').click();const layer=document.querySelector('#click-effects');const value=layer.querySelector('.floating-number');return {ripple:layer.querySelectorAll('.click-indicator').length,values:layer.querySelectorAll('.floating-number').length,art:layer.querySelectorAll('.click-emoji-pop img').length,label:value?.textContent,durations:[...layer.children].map(n=>n.getAnimations()[0]?.effect.getTiming().duration),bounds:value?.getBoundingClientRect().toJSON()};});
 assert.equal(evidence.ripple,2,'each click needs a ripple');assert.equal(evidence.values,2,'each click needs a floating value');assert.equal(evidence.art,2,'each click needs independent random art');assert.match(evidence.label,/^\+\d+\.\d$/);assert.ok(evidence.durations.includes(1500));assert.ok(evidence.durations.includes(1000));assert.ok(evidence.bounds.left>=6&&evidence.bounds.right<=384,'floating value must fit viewport');await page.waitForTimeout(1650);assert.equal(await page.locator('#click-effects > *').count(),0);assert.equal(await page.locator('#bufo img').evaluate(n=>n.getAnimations().length),0);assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'passed',...evidence}));}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
